// compare_transform.cpp
// C++ side: load Python-exported PCA(K=50), transform 100 samples, compare.
// Prints explained variance for every component and the full transform.

#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <vector>

#include "pca.hpp"
#include "lcg_pca50_params.hpp"   // generated by compare_transform.py

static constexpr uint32_t SEED  = 143;
static constexpr int      N     = 3000;
static constexpr int      D     = 100;
static constexpr int      K     = 50;
static constexpr int      N_TX  = 100;

// ──────────────────────────────────────── LCG + data
inline uint32_t lcg_step(uint32_t& s) noexcept {
    s = 1664525u * s + 1013904223u;
    return s;
}

static std::vector<std::vector<double>> generate() {
    uint32_t s = SEED;
    std::vector<std::vector<double>> data(N, std::vector<double>(D));
    for (int i = 0; i < N; ++i)
        for (int j = 0; j < D; ++j)
            data[i][j] = static_cast<double>(lcg_step(s)) / 4294967296.0;
    return data;
}

// ══════════════════════════════════════════════════════════════════
int main() {
    // ── generate + center ────────────────────────────────────────
    auto raw = generate();

    std::vector<double> means(D, 0.0);
    for (const auto& row : raw)
        for (int j = 0; j < D; ++j) means[j] += row[j];
    for (auto& m : means) m /= static_cast<double>(N);

    auto X = raw;
    for (auto& row : X)
        for (int j = 0; j < D; ++j) row[j] -= means[j];

    // ── load Python-exported PCA ──────────────────────────────────
    auto pca_loaded = lcg_pca50::make_pca();

    const auto& ev     = pca_loaded.explained_variance_values();   // K eigenvalues
    const auto& er     = pca_loaded.explained_variance_ratio();    // K ratios
    const double tv    = lcg_pca50::total_variance;

    // Compute cumulative ratio
    std::vector<double> cum(K);
    cum[0] = er[0];
    for (int k = 1; k < K; ++k) cum[k] = cum[k-1] + er[k];

    std::cout << std::fixed;
    std::cout << "=== C++ PCA  (K=" << K << ", loaded Python params)"
              << "  total_variance=" << std::setprecision(6) << tv << " ===\n\n";

    std::cout << "  " << std::setw(4)  << "dim"
              << "  " << std::setw(12) << "eigenvalue"
              << "  " << std::setw(10) << "ratio"
              << "  " << std::setw(10) << "cumulative" << "\n";
    std::cout << "  " << std::string(4,  '-')
              << "  " << std::string(12, '-')
              << "  " << std::string(10, '-')
              << "  " << std::string(10, '-') << "\n";
    for (int k = 0; k < K; ++k) {
        std::cout << "  " << std::setw(4)  << k
                  << "  " << std::setw(12) << std::setprecision(8) << ev[k]
                  << "  " << std::setw(10) << std::setprecision(8) << er[k]
                  << "  " << std::setw(10) << std::setprecision(8) << cum[k] << "\n";
    }
    std::cout << "\n  Variance retained by " << K << " components: "
              << std::setprecision(4) << cum[K-1] * 100.0 << "%\n\n";

    // ── transform first 100 samples ──────────────────────────────
    std::vector<std::vector<double>> X100(X.begin(), X.begin() + N_TX);
    auto Xt = pca_loaded.transform(X100);

    std::cout << "=== C++ transform  (" << N_TX << " samples x " << K << " components) ===\n";
    for (int i = 0; i < N_TX; ++i) {
        std::cout << "[" << std::setw(3) << i << "]";
        for (int j = 0; j < K; ++j)
            std::cout << " " << std::setw(11) << std::setprecision(8)
                      << std::showpos << Xt[i][j];
        std::cout << "\n";
    }

    // ── compare with Python reference ────────────────────────────
    std::ifstream ref("lcg_tx100_ref.txt");
    if (!ref) {
        std::cerr << "\nERROR: lcg_tx100_ref.txt not found."
                     " Run compare_transform.py first.\n";
        return 1;
    }

    std::cout << std::noshowpos;
    std::cout << "\n=== Comparison  |C++ − Python|  per row  (max over " << K << " components) ===\n";

    double global_max  = 0.0;
    double global_sumsq = 0.0;
    for (int i = 0; i < N_TX; ++i) {
        std::string line;
        std::getline(ref, line);
        std::istringstream ss(line);
        double row_max = 0.0;
        for (int j = 0; j < K; ++j) {
            double py_val; ss >> py_val;
            double diff  = std::abs(Xt[i][j] - py_val);
            row_max      = std::max(row_max, diff);
            global_sumsq += diff * diff;
        }
        global_max = std::max(global_max, row_max);
        std::cout << "  row [" << std::setw(3) << i << "]  max_diff = "
                  << std::setprecision(2) << std::scientific << row_max << "\n";
    }

    double rms = std::sqrt(global_sumsq / static_cast<double>(N_TX * K));
    std::cout << "\n  ┌─ Summary ────────────────────────────────────────\n"
              << "  │  max_abs_diff : " << std::setprecision(3) << std::scientific << global_max  << "\n"
              << "  │  rms_diff     : " << rms  << "\n"
              << "  └──────────────────────────────────────────────────\n"
              << "  " << (global_max < 1e-8 ? "ALL VALUES MATCH  (max diff < 1e-8)"
                                             : "*** MISMATCH DETECTED ***") << "\n";

    return (global_max < 1e-8) ? 0 : 1;
}
