// Deep audit — C++ side.
//
// Generates the same 3000x100 LCG dataset as test_audit.py, fits PCA
// via Jacobi, then cross-checks against Python-exported parameters.
// Reads lcg_expected.txt (written by test_audit.py) for reference values.

#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

#include "pca.hpp"
#include "lcg_pca_params.hpp"  // generated by test_audit.py

static constexpr uint32_t SEED = 143;
static constexpr int N = 3000, D = 100, K = 10;

// ──────────────────────────────────────── LCG
inline uint32_t lcg_step(uint32_t& s) noexcept {
    s = 1664525u * s + 1013904223u;   // wraps automatically mod 2^32
    return s;
}

// ──────────────────────────────────────── data generation
static std::vector<std::vector<double>> generate(uint32_t seed) {
    std::vector<std::vector<double>> data(N, std::vector<double>(D));
    for (int i = 0; i < N; ++i)
        for (int j = 0; j < D; ++j)
            data[i][j] = static_cast<double>(lcg_step(seed)) / 4294967296.0;
    return data;
}

// ──────────────────────────────────────── reporting
static bool g_all_pass = true;

static void check(const char* name, bool ok) {
    std::cout << "  [" << (ok ? "PASS" : "FAIL") << "] " << name << "\n";
    if (!ok) g_all_pass = false;
}

static void hdr(const std::string& title) {
    std::cout << "\n" << std::string(62, '-') << "\n  " << title << "\n"
              << std::string(62, '-') << "\n";
}

// ══════════════════════════════════════════════════════════════════════
int main() {
    // ── read reference values written by test_audit.py ──────────────
    std::ifstream ref("lcg_expected.txt");
    if (!ref) {
        std::cerr << "ERROR: lcg_expected.txt not found.\n"
                  << "       Run `python3 test_audit.py` first.\n";
        return 1;
    }

    std::vector<uint32_t> exp_lcg(10);
    for (auto& v : exp_lcg) ref >> v;

    std::vector<double> exp_raw(10);       // raw[0,:5] + raw[1,:5]
    for (auto& v : exp_raw) ref >> v;

    std::vector<double> exp_evals(K);
    for (auto& v : exp_evals) ref >> v;

    std::vector<double> exp_tx(5 * K);    // transform of rows 0..4
    for (auto& v : exp_tx) ref >> v;

    // ═══════════════════════════════════════════ 1. LCG sequence
    hdr("LCG sequence  (seed=143, first 10 raw uint32 states)");
    uint32_t s = SEED;
    bool lcg_ok = true;
    for (int i = 0; i < 10; ++i) {
        uint32_t v = lcg_step(s);
        bool match = (v == exp_lcg[i]);
        std::cout << "  step " << std::setw(2) << i
                  << ":  cpp=" << std::setw(12) << v
                  << "   py=" << std::setw(12) << exp_lcg[i]
                  << (match ? "" : "  *** MISMATCH ***") << "\n";
        if (!match) lcg_ok = false;
    }
    check("LCG bit-exact  (all 10 uint32 states identical)", lcg_ok);

    // ═══════════════════════════════════════════ 2. Raw data
    hdr("Raw data generation");
    auto raw = generate(SEED);
    bool raw_ok = true;
    for (int ri = 0; ri < 2; ++ri) {
        for (int ci = 0; ci < 5; ++ci) {
            double v = raw[ri][ci];
            double e = exp_raw[ri * 5 + ci];
            bool match = (v == e);   // should be bit-exact
            std::cout << "  raw[" << ri << "][" << ci << "]"
                      << "  cpp=" << std::setprecision(10) << std::fixed << v
                      << "  py="  << e
                      << (match ? "" : "  *** MISMATCH ***") << "\n";
            if (!match) raw_ok = false;
        }
    }
    check("Raw float values bit-exact  (uint32/2^32 conversion)", raw_ok);

    // ═══════════════════════════════════════════ 3. Centering
    hdr("Centering");
    // Compute column means (sequential sum — differs from numpy pairwise)
    std::vector<double> col_means(D, 0.0);
    for (const auto& row : raw)
        for (int j = 0; j < D; ++j)
            col_means[j] += row[j];
    for (auto& m : col_means) m /= static_cast<double>(N);

    std::vector<std::vector<double>> X = raw;
    for (auto& row : X)
        for (int j = 0; j < D; ++j)
            row[j] -= col_means[j];

    // Verify residual means
    std::vector<double> residuals(D, 0.0);
    for (const auto& row : X)
        for (int j = 0; j < D; ++j)
            residuals[j] += row[j];
    double max_res = 0.0;
    for (int j = 0; j < D; ++j)
        max_res = std::max(max_res, std::abs(residuals[j] / N));

    double min_mean = col_means[0], max_mean = col_means[0];
    for (double m : col_means) { min_mean = std::min(min_mean, m); max_mean = std::max(max_mean, m); }
    std::cout << "  col means   min=" << std::setprecision(6) << std::fixed << min_mean
              << "  max=" << max_mean << "\n";
    std::cout << "  max residual mean after centering: "
              << std::setprecision(2) << std::scientific << max_res << "\n";
    check("Max col residual mean < 1e-12", max_res < 1e-12);

    // ═══════════════════════════════════════════ 4. Covariance diagonal
    hdr("Covariance diagonal  (first 5 features, expect ≈ 0.0833 for Uniform[0,1])");
    for (int j = 0; j < 5; ++j) {
        double ss = 0.0;
        for (const auto& row : X) ss += row[j] * row[j];
        std::cout << "  cov[" << j << "," << j << "] = "
                  << std::setprecision(6) << std::fixed << ss / (N - 1) << "\n";
    }

    // ═══════════════════════════════════════════ 5. PCA fit (Jacobi)
    hdr("PCA fit  (C++ Jacobi eigendecomposition, K=10)");
    pca::PCA<double> p(K);
    p.fit(X, 64);

    const auto& evals  = p.explained_variance_values();
    const auto& ratios = p.explained_variance_ratio();
    double rsum = 0.0;
    for (double v : ratios) rsum += v;

    std::cout << "  eigenvalues:";
    for (double v : evals)  std::cout << std::fixed << std::setprecision(6) << "  " << v;
    std::cout << "\n  ratios     :";
    for (double v : ratios) std::cout << "  " << v;
    std::cout << "\n  ratio sum  :  " << std::setprecision(8) << rsum << "\n";

    // ═══════════════════════════════════════════ 6. Eigenvalue comparison
    hdr("Eigenvalue comparison  (C++ Jacobi  vs  Python numpy.linalg.eigh)");
    bool eval_ok = true;
    double max_eval_rel = 0.0;
    for (int k = 0; k < K; ++k) {
        double rel = std::abs(evals[k] - exp_evals[k]) /
                     (std::abs(exp_evals[k]) + 1e-15);
        max_eval_rel = std::max(max_eval_rel, rel);
        std::cout << "  [" << k << "]  cpp=" << std::setprecision(8) << std::fixed << evals[k]
                  << "  py=" << exp_evals[k]
                  << "  rel_err=" << std::setprecision(2) << std::scientific << rel << "\n";
        if (rel > 1e-6) eval_ok = false;
    }
    std::cout << "  max_rel_err = " << std::setprecision(2) << std::scientific << max_eval_rel << "\n";
    check("All eigenvalues  rel_err < 1e-6", eval_ok);

    // ═══════════════════════════════════════════ 7. Transform comparison
    hdr("Transform  (C++ Jacobi fit  vs  Python eigh fit, sign-aligned, 5 rows)");
    std::vector<std::vector<double>> X5(X.begin(), X.begin() + 5);
    auto Xt_cpp = p.transform(X5);

    // Per-component sign alignment based on row 0
    std::vector<double> sgn(K, 1.0);
    for (int j = 0; j < K; ++j)
        if (Xt_cpp[0][j] * exp_tx[j] < 0.0) sgn[j] = -1.0;

    bool tx_ok = true;
    double max_tx_rel = 0.0;
    for (int i = 0; i < 5; ++i)
        for (int j = 0; j < K; ++j) {
            double v   = sgn[j] * Xt_cpp[i][j];
            double e   = exp_tx[i * K + j];
            double rel = std::abs(v - e) / (std::abs(e) + 1e-10);
            max_tx_rel = std::max(max_tx_rel, rel);
            if (rel > 1e-5) tx_ok = false;
        }

    // Print row 0 for visual inspection
    std::cout << "  cpp row 0:";
    for (int j = 0; j < K; ++j)
        std::cout << std::fixed << std::setprecision(5) << "  " << sgn[j] * Xt_cpp[0][j];
    std::cout << "\n   py row 0:";
    for (int j = 0; j < K; ++j)
        std::cout << "  " << std::setprecision(5) << exp_tx[j];
    std::cout << "\n  max_rel_err = " << std::setprecision(2) << std::scientific << max_tx_rel << "\n";
    check("Transform (sign-aligned) rel_err < 1e-5  (5 rows × K cols)", tx_ok);

    // ═══════════════════════════════════════════ 8. Cross-check: loaded params
    hdr("Cross-check  (Python-exported params loaded in C++  vs  Python output)");
    auto pca_loaded = lcg_pca::make_pca();
    auto Xt_loaded  = pca_loaded.transform(X5);

    bool cross_ok = true;
    double max_cross = 0.0;
    for (int i = 0; i < 5; ++i)
        for (int j = 0; j < K; ++j) {
            double diff = std::abs(Xt_loaded[i][j] - exp_tx[i * K + j]);
            max_cross   = std::max(max_cross, diff);
            if (diff > 1e-10) cross_ok = false;
        }
    std::cout << "  max_abs_err = " << std::setprecision(2) << std::scientific << max_cross << "\n";
    check("Loaded-params transform  abs_err < 1e-10  (5 rows × K cols)", cross_ok);

    // ═══════════════════════════════════════════ 9. Batched transform
    hdr("Batched transform  (C++ loaded params, batch_size=2 vs single pass)");
    auto Xt_batch = pca_loaded.transform(X5, 2);
    bool batch_ok = true;
    double max_batch = 0.0;
    for (int i = 0; i < 5; ++i)
        for (int j = 0; j < K; ++j) {
            double diff = std::abs(Xt_batch[i][j] - Xt_loaded[i][j]);
            max_batch   = std::max(max_batch, diff);
            if (diff > 1e-15) batch_ok = false;
        }
    std::cout << "  max_abs_err = " << std::setprecision(2) << std::scientific << max_batch << "\n";
    check("Batched transform matches single-pass  abs_err < 1e-15", batch_ok);

    // ═══════════════════════════════════════════ 10. n_components clamping
    hdr("Edge case: n_components > D");
    pca::PCA<double> p_big(D + 50);
    p_big.fit(X, 64);
    int actual_k = static_cast<int>(p_big.explained_variance_values().size());
    std::cout << "  requested K=" << (D + 50) << "  actual K=" << actual_k
              << "  (should equal D=" << D << ")\n";
    check("n_components clamped to D when n_components > D", actual_k == D);

    // ═══════════════════════════════════════════ 11. Error handling
    hdr("Error handling");
    bool e1 = false, e2 = false, e3 = false, e4 = false, e5 = false;

    try { pca::PCA<double> bad(0); }
    catch (const std::invalid_argument&) { e1 = true; }

    try { pca::PCA<double> tmp(5); tmp.transform({{1.0, 2.0}}); }
    catch (const std::runtime_error&) { e2 = true; }

    try { pca::PCA<double> tmp(5); tmp.fit({{1.0, 2.0}}); }  // N=1 < 2
    catch (const std::invalid_argument&) { e3 = true; }

    try { pca::PCA<double> tmp(5); tmp.fit({{1.0}, {2.0, 3.0}}); }  // ragged
    catch (const std::invalid_argument&) { e4 = true; }

    try { pca::PCA<double> tmp(5); tmp.fit({}); }  // empty X
    catch (const std::invalid_argument&) { e5 = true; }

    check("n_components=0          → invalid_argument", e1);
    check("transform before fit    → runtime_error",    e2);
    check("fit with N=1            → invalid_argument", e3);
    check("fit with ragged rows    → invalid_argument", e4);
    check("fit with empty X        → invalid_argument", e5);

    // ═══════════════════════════════════════════ summary
    std::cout << "\n" << std::string(62, '=') << "\n";
    if (g_all_pass)
        std::cout << "  ALL TESTS PASSED\n";
    else
        std::cout << "  *** SOME TESTS FAILED ***\n";
    std::cout << std::string(62, '=') << "\n";

    return g_all_pass ? 0 : 1;
}
